apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/lgao-arccorp-com/my-spring-prom:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/lgao-arccorp-com/my-spring-prom:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: my-spring-prom
        chartPath: charts/my-spring-prom
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/lgao-arccorp-com/my-spring-prom"
          image.tag: "{{.TAG}}"
